name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: [self-hosted, linux]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r ~/test/lambda-cicd/lambda-functions/function1/requirements.txt
          pip install -r ~/test/lambda-cicd/lambda-functions/function2/requirements.txt
          pip install pylint
          pip install pytest

      - name: Lint code
        run: |
          pylint ~/test/lambda-cicd/lambda-functions/function1/lambda_function1.py
          pylint ~/test/lambda-cicd/lambda-functions/function2/lambda_function2.py

      - name: Run tests
        run: |
          pytest ~/test/lambda-cicd/lambda-functions/function1/test_lambda_function1.py
          pytest ~/test/lambda-cicd/lambda-functions/function2/test_lambda_function2.py
