name: Deploy Lambda Functions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        function: [function1, function2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        cd ~/test/lambda-cicd/lambda-functions/${{ matrix.function }}
        pip install -r requirements.txt

    - name: Lint code
      run: |
        cd ~/test/lambda-cicd/lambda-functions/${{ matrix.function }}
        pylint --rcfile=../../.pylintrc main.py

    - name: Run unit tests
      run: |
        cd ~/test/lambda-cicd/lambda-functions/${{ matrix.function }}
        python -m unittest discover -s .
    
    - name: Deploy to LocalStack
      run: |
        cd ~/test/lambda-cicd/lambda-functions/${{ matrix.function }}
        zip -r function.zip .
        aws --endpoint-url=http://localhost:4566 lambda create-function --function-name ${{ matrix.function }} \
          --runtime python3.10 --role arn:aws:iam::123456789012:role/execution_role \
          --handler main.lambda_handler --zip-file fileb://function.zip