name: Deploy Lambdas

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies and run lint for Lambda 1
      working-directory: ./lambdas/lambda1
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pylint handler.py

    - name: Install dependencies and run lint for Lambda 2
      working-directory: ./lambdas/lambda2
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pylint handler.py

    - name: Run unit tests
      run: |
        pytest

    - name: Deploy Lambda 1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        zip -r lambda1.zip .
        aws lambda update-function-code --function-name lambda1 --zip-file fileb://lambda1.zip
        aws lambda update-function-configuration --function-name lambda1 --environment Variables={KEY=value}

    - name: Deploy Lambda 2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        zip -r lambda2.zip .
        aws lambda update-function-code --function-name lambda2 --zip-file fileb://lambda2.zip
        aws lambda update-function-configuration --function-name lambda2 --environment Variables={KEY=value}